
name: Flutter CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Create credentials.json from secret
      run: |
        mkdir -p assets
        echo "${{ secrets.CONFIG_FILE }}" > assets/credentials.json

    - name: Analyze code
      run: flutter analyze

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

