name: Flutter CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true  
    # - name: Setup key
    #   uses: webfactory/ssh-agent@v0.7.0
    #   with:
    #       ssh-private-key: ${{ secrets.SSH_TOKEN}}
    - name: bundle install
      run: bundle install
      working-directory: android
    - name: Setup Bundler
      run: |
        bundle init
        echo "gem 'fastlane'" >> Gemfile
        echo "gem 'fastlane-plugin-firebase_app_distribution'" >> Gemfile
        bundle install --path vendor/bundle
        
    - name: Setup Fastlane
      working-directory: android
      run: |
        mkdir -p fastlane
        echo "${{ secrets.FASTFILE }}" > fastlane/Fastfile
        
    - name: Install fastlane
      run: sudo gem install fastlane
      
    - name: Install Bundler dependencies
      run: |
        bundle install --path vendor/bundle
        
    - name: Add Firebase App Distribution Plugin
      run: |
        bundle exec fastlane add_plugin firebase_app_distribution
    
    - name: Fastlane upload firebase distribute
      working-directory: android
      run: bundle exec fastlane firebase_distribute
      
    - name: Upload to Firebase
      working-directory: android
      run: bundle exec fastlane firebase_distribute
